server:
  port: 3000
spring:
  datasource:
    username: root
    password: Lso3XPmjXBMsgXUiBdHoDBo+usW6fScXlD755g6qcGkd223qGwpDfOSNMpODXvvur1yhbm8mm2LD8OcyOYpyvw==
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.213.50:3306/ms-club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSl=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      min-idle: 20
      max-wait: 60000
      max-active: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 117.72.15.198
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: cp1234
    # 连接超时时间
    timeout: 2s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接

publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI0OtFe6vbXxW1M6/15LMm7/ElvZIfralWLXLeZ1p93wxmND/mKM5ibfsz3idMOJ9tSQLOYhY4K/X7EcsEXjWhECAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml

  elasticsearch:
    rest:
      uris: [ "117.72.15.198:9200" ]
      connection-timeout: 10s

es:
  cluster:
    esConfigs[0]:
      name: 410767cf0cec
      nodes: 117.72.15.198:9200

management:
  health:
    elasticsearch:
      enabled: false
#es:
#  cluster:
#    esConfigs[0]:
#      name: 410767cf0cec
#      nodes: 117.72.15.18:9200
#


xxl:
  job:
    admin:
      addresses: http://117.72.15.198:8090/xxl-job-admin

    accessToken: default_token
    executor:
      appname: ms-club-subjcet
      address:
      ip: 120.26.213.50
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

#可以知道数据库详细的查询信息
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl